apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    app: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
      evaluation_interval: 5s
    scrape_configs:
      - job_name: "userservice"
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ["user-service-api:8085"]
      - job_name: "productservice"
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ["product-service-api:8067"]
      - job_name: "apigateway"
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ["api-gateway-api:8767"]
      - job_name: "eurekaserver"
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ["eureka-service:8761"]          
      - job_name: "favouriteservice"
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ["favourite-service-api:9096"]
      - job_name: "orderservice"
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ["order-service-api:8086"]  
      - job_name: "paymentservice"
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ["payment-service-api:8087"]
      - job_name: "shippingservice"
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ["shipping-service-api:8090"]            
      - job_name: "proxyclient"
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ["proxy-client-api:8091"]    
      - job_name: "zipkin"
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ["zipkin-service:9411"]                   